name: 'Upload to onion service'
description: 'Uploads files to an onion service using rsync on Tor.'
author: 'Sebastian Wieland'
inputs:
  source_dir:
    required: true
    description: 'Local source directory.'

  destination_dir:
    required: true
    description: 'Remote destination directory.'
  
  ssh_user: 
    required: true
    description: 'Username used for remote authentication.'
  
  ssh_privatekey:
    required: true
    description: 'Private key used for remote authentication. Passphrase authentication is (at the moment) not supported.'
  
  ssh_port:
    required: false
    default: 22
    description: 'SSH Port. Default: 22'
  
  onion_host:
    required: true
    description: 'Onion hostname of the remote server WITHOUT the .onion suffix.'
      
  onion_client_auth_privatekey:
    required: false
    description: 'If Client Authorization is active on the onion service, provide a valid private key.'
  
  delete:
    required: false
    description: 'Delete extraneous files from destination directories.'
    default: false
  
runs:
  using: 'docker'
  image: 'Dockerfile'
    

branding:
  icon: copy
  color: purple