name: Rsync Onion
on: 
  push:
    branches:
      - 'feature/*'
jobs:
  ci:
    name: Test action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate dummy file
        run: mkdir -p dist && date > dist/currentdate.txt
      
      - name: Rsync to onion service, keep remote files
        uses: ./
        with:
          source_dir: ./dist/
          destination_dir: /home/pi/gh-destination/keep
          ssh_user: pi
          ssh_privatekey: ${{ secrets.SSH_PRIVATEKEY }}
          ssh_disable_strict_host_key_checking: true
          onion_host: ${{ secrets.ONION_HOST }}
          onion_client_auth_privatekey: ${{ secrets.ONION_CLIENT_AUTH_PRIVATEKEY }}

      - name: Rsync to onion service, delete extraneous remote files
        uses: ./
        with:
          source_dir: ./dist/
          destination_dir: /home/pi/gh-destination/delete
          ssh_user: pi
          ssh_privatekey: ${{ secrets.SSH_PRIVATEKEY }}
          ssh_host_fingerprint: ${{ secrets.SSH_HOST_FINGERPRINT }}
          onion_host: ${{ secrets.ONION_HOST }}
          onion_client_auth_privatekey: ${{ secrets.ONION_CLIENT_AUTH_PRIVATEKEY }}
          delete: true
          before_rsync_command: 'echo "before" > /home/pi/gh-destination/test.txt'
          after_rsync_command: 'echo "after" >> /home/pi/gh-destination/test.txt'